// Generated by CoffeeScript 1.7.1
var Vue, app;

app = require('./app');

Vue = require('vue');

app.menu = new Vue({
  el: '#menu',
  data: app.get('menu'),
  computed: {},
  methods: {
    createTask: function(event) {
      this.$data.working.unshift({
        title: '',
        content: '...'
      });
      return event.stopPropagation();
    },
    doWork: function(index) {
      var taskList;
      taskList = this.$data.futures.splice(index, 1);
      return this.$data.working.unshift(taskList[0]);
    },
    doFutures: function(index) {
      var taskList;
      taskList = this.$data.working.splice(index, 1);
      return this.$data.futures.unshift(taskList[0]);
    },
    doHistory: function(index) {
      var taskList;
      taskList = this.$data.working.splice(index, 1);
      this.$data.history.unshift({
        title: taskList[0].title,
        content: taskList[0].content,
        finish: '...'
      });
      return this.$data.history.splice(40);
    },
    doFocus: function(index) {
      var taskList;
      taskList = this.$data.working.splice(index, 1);
      return this.$data.working.unshift(taskList[0]);
    },
    doFocusFutures: function(index) {
      var taskList;
      taskList = this.$data.futures.splice(index, 1);
      return this.$data.futures.unshift(taskList[0]);
    },
    doRemove: function(index) {
      return this.$data.working.splice(index, 1);
    }
  }
});

Vue.directive('focus-editable', {
  bind: function() {
    return setTimeout((function(_this) {
      return function() {
        var range, sel, target;
        range = document.createRange();
        sel = window.getSelection();
        target = _this.el;
        range.setStartBefore(target);
        range.setEndAfter(target);
        sel.removeAllRanges();
        sel.addRange(range);
        return _this.el.focus();
      };
    })(this));
  }
});
